### ISSUE TITLE
RPM-Face-Tracing in Godot using C#

### ISSUE THREAD

**Issue by GeorgeS2019** [srcnalt/rpm-face-tracking#1]
[Import RPM Avatar to Godot](https://github.com/srcnalt/ReadyPlayerMe-Godot-Test/issues/1#issuecomment-1552417084)

**Comment by GeorgeS2019** [comment]
```typescript
import { Canvas, useFrame, useGraph } from '@react-three/fiber';

 const { scene } = useGLTF(`${url}?morphTargets=ARKit&textureAtlas=1024`);
  const { nodes } = useGraph(scene);


  useEffect(() => {
    headMesh = (nodes.Wolf3D_Head || nodes.Wolf3D_Avatar);
  }, [nodes, url]);
```

**Comment by srcnalt** [comment]
This is neither Godot, nor a C# project, I will have to close the issue. Feel free to use the code example to convert the logic into Godot/C#.

**Comment by GeorgeS2019** [comment]
@srcnalt 
It is fine to close it. 
We now have Mediapipe webcam capture to work, my plan is to engage more Godot users to automate Unity to Godot involving RPM.

**Comment by GeorgeS2019** [comment]
@srcnalt 
We now have working Godot4 Mediapiple with complete facial landmarks Godot GDMP

It would be great to have [a demo using Godot GDMP ](https://github.com/srcnalt/rpm-godot-sdk/issues/1#issue-2235705500)to drive ReadyPlayerMe using RPM-Godot-SDK

**Comment by srcnalt** [comment]
Great work, I will check it when I get to my PC.
