### ISSUE TITLE
hand and foot movement

### ISSUE THREAD

**Issue by jfdream** [srcnalt/rpm-face-tracking#2]
Great project. Can you provide more examples of hand and foot movement

**Comment by srcnalt** [comment]
Hi @jfdream,

I am planning to work on hand and fullbody tracking too. Will drop videos and repo for those when it's done.

**Comment by MuhammadAasharibNawshad** [comment]
Hi @srcnalt. Thanks for the awesome project. I wanted to ask whether you have implemented fullbody tracking too and its repository is available somewhere?

**Comment by srcnalt** [comment]
Hi @MuhammadAasharibNawshad, I did check it back then but tracking was not good enough. Should be done easily but it does not support 3D position, you will need to decide the position on a plane coordinate system,
